### ISSUE TITLE
not support m0 tarmac log

### ISSUE THREAD

**Issue by Johnmc104** [ARM-software/tarmac-trace-utilities#13]
need add features

**Comment by Johnmc104** [comment]
[elf_and_log.zip](https://github.com/ARM-software/tarmac-trace-utilities/files/12711683/elf_and_log.zip)

**Comment by statham-arm** [comment]
Thanks for this sample. Indeed, this is a type of Tarmac that TTU's parser is not yet able to handle. At a glance, the differences seem to be:
1. there's no space between the numeric timestamp and the unit ("396ns" instead of "396 ns")
2. the instruction-set state and CPU mode fields are missing from `IT` and `IS` instruction lines, along with the `:` that usually separates those from the instruction.

Can you say something about where this trace came from? Your title suggests that the CPU was Cortex-M0, but what was the Tarmac-generating tool?

As a workaround for the moment, I found I was able to reprocess your trace into one that TTU can handle using the following Perl one-liner:
```
perl -pe 's{^(\d+)(ns)}{$1 $2}; s{^(\S+ \S+ (IT|IS) \S+ \S+)}{$1 T svc_s :}' tarmac1.log > fixed.log
```

**Comment by Johnmc104** [comment]
This is tarmac rtl module from Cortex-M0-AT510-r0p0-00rel0

**Comment by statham-arm** [comment]
I've just pushed changes that should enable these tools to parse that Tarmac file.

Unfortunately, they still can't do it by default, because the missing instruction-set state (compared to the usual format) needs to be filled in. But there's a new command-line option ``--implicit-thumb`` that should allow this file to be parsed.
