### ISSUE TITLE
set CURSES_NEED_NCURSES by default for unix

### ISSUE THREAD

**Issue by chargr** [ARM-software/tarmac-trace-utilities#19]
When trying to use ncurses from an external path set in `CMAKE_SYSTEM_PREFIX_PATH`, cmake's `FindCurses.cmake` still locates `/usr/lib64/libcurses.so` first.

```
[root@e4549d748103 tmp]# cat /usr/lib64/libcurses.so
INPUT(-lncurses)
```

https://cmake.org/cmake/help/latest/module/FindCurses.html

Setting `CURSES_NEED_NCURSES` will avoid looking for the libcurses library and look for libncurses first and correctly locate the inteded library in `CMAKE_SYSTEM_PREFIX_PATH`

https://github.com/chargr/tarmac-trace-utilities/commit/a1da7de73d109783ac8a245174dc46a6483e0681

**Comment by statham-arm** [comment]
If I've understood correctly, setting `CURSES_NEED_NCURSES` would make the build fail in an environment where only a 'vanilla' curses is available? That doesn't seem like a good side effect.

It sounds as if what you really want is a setting along the lines of `CURSES_PREFER_NCURSES`, rather than `NEED` – you want to look for ncurses first, and use it if you find it, and only fall back to vanilla curses if you can't get ncurses.

Would it work to try `FindCurses` twice, once with `CURSES_NEED_NCURSES`, and then again as a fallback if that fails? Something like this (not tested):
```cmake
set(CURSES_NEED_NCURSES TRUE)
find_package(Curses)
if(NOT CURSES_FOUND)
    set(CURSES_NEED_NCURSES FALSE)
    find_package(Curses ${REQUIRED_PACKAGE})
endif()
```

**Comment by chargr** [comment]
i dont think that is necessary because on non-windows the include is

https://github.com/ARM-software/tarmac-trace-utilities/blob/6969ad925f68ca4bbbe3f05e8c80b25ff654afe0/browser/curses.cpp#L45

**Comment by statham-arm** [comment]
Good catch, thank you – that is also a mistake! I should be including whichever curses header turned out to exist. I wrote the code a long time before the cmake file, and didn't spot that.

**Comment by statham-arm** [comment]
I've pushed changes that address this, and also make the tools build on systems with only a `libcurses` and no `libncurses` (such as NetBSD). Please reopen if you still have a problem!
