### ISSUE TITLE
Question about implementation of index file

### ISSUE THREAD

**Issue by ninipa** [ARM-software/tarmac-trace-utilities#8]
Hi,
Sorry to bother you! I'm learning tarmac based sw debug and just found this project which is quite useful. However, before fully understanding the implementation, I have a very initial question/confusion about the fundamental implementation of index file and how it being used by other tools.
For example, I tried play tarmac-browser, it immediately shows reg and memory info once I jump to certain line of original tarmac file. It seems the reg/memory info of certain tarmac line is stored in the index file so that it can be represented in browser immediately (like, the reg/memory info at that moment of each line in the trace are stored). But in theory, it's almost impossible to store such huge info in the index file (and I see the size of index file looks OK).
I'm wondering, if index file only contains intermediate info, then other tools like browser still need kind of processing to get reg/memory info of certain line of trace? If so, what if the size of original tarmac trace is large (for example, GB level), despite of the index generation time, any potential performance risk when browser to represent info?
Thank you!

**Comment by ninipa** [comment]
Hi Simon,

Thanks for the detailed description!! Now it's more clear to me. Here're my understanding about node sharing, could you please help confirm if it's correct?
With experiments, I see each node in seqtree has an attribute "Root of memory tree: <memtree-offset>", thus there're many memtrees. Let's make an exmaple:

_Assuming at T1, T2 and T3, there're 3 reg/memory new events. I can see there're 3 memtrees are generated individually and linked to corresponding seqtree node. And I see the memroot offset of each memtree looks incremental, so I think the storage of memtree info in index file is like:
**||-- T1 memtree --||-- T2 memtree with more info --||-- T3 memtree which is larger than T2        --||**
I see some un-touched addresses points to the same offset in the 3 memtrees, I think this is your "space saving", right? However, the space to store memtree info itself is duplicated and getting larger, right? Then maybe near the end of simulation, the memtree in last seq node is the largest, right?_

Therefore and in addition, I have basically two questions:
- I think the backend searching performance is good because of your amazing data structure. Then how about the performance of generating the index file? Have you ever tried processing large tarmac file (e.g. tarmac of kernel boot), what is your experience of processing large tarmac file?
- Any risk about the size of index file if the tarmac is large?

BTW, can I get large tarmac file somewhere to try?

Thank you again!!

**Comment by statham-arm** [comment]
The _whole memtree_ of the final seq node will likely be the largest, yes. But the _new nodes_ added at that final step will still be small. Your example diagram looks more like

**||-- T1 memtree --||-- nodes in the T2 memtree that differ from T1's --||-- nodes in T3 memtree that differ from T2's --||**

and in each section, the number of nodes is logarithmic in the overall number of nodes in the tree.

Asymptotically, indexing performance should be O(n log n). So, slower than linear time, and getting gradually slower and slower on large files, but still not by very much.

The size of the index file is also O(n log n), because to a first approximation, the work done during indexing is all creating new nodes of various trees to append to the index file.

You're right that the index file is potentially quite large. O(n log n) space can get surprisingly big. I've never personally tried this system on a trace as large as a Linux kernel boot; my own uses of it have always been debugging standalone embedded programs much smaller than a kernel.

(So I don't have a really big trace file for you, I'm afraid. I can only suggest finding a large program of your choice, and running it on a model that can produce Tarmac output, such as an Arm Fast Model.)

I've occasionally thought that it would be nice to have a choice of index data structures, trading off space usage against query speed, by means of having multiple data-structure systems in the code and an identifier field in the index file saying which one was in use. Then for a really big trace you could fall back to a more compact indexing system, at the cost of queries taking longer (because maybe searching the simpler index takes O(n) time, or something). But that's a lot of work that I haven't found time to do!

Yet another possible indexing system for memory contents would be to build up a list of memory writes of fixed size, e.g. in the form (address, 4 bytes of data, timestamp). They would naturally be ordered by timestamp. But then, when the index file is finalized, you sort them into order by the key (address, timestamp). And then you can retrieve the contents of _this_ address at _that_ time by binary search (and the element just before the query key will be the most recent write to the address). That system is linear in space usage, and still permits log-time lookups, but has some downsides in the fine detail (e.g. the division of memory into fixed-size chunks), and also I'm not sure how it would support the retroactive effect of tracing a memory read.

**Comment by statham-arm** [comment]
I'm closing this inactive issue, since it was more of a query than a bug report, and I think it's all been answered.
